import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        bg: '#ffffff',
        surface: '#fafafa',
        'surface-alt': '#f0f0f0',
        border: '#d8d8d8',
        'border-focus': '#a0a0a0',
        primary: '#1a1a1a',
        secondary: '#555555',
        tertiary: '#888888',
        accent: '#a0a0a0',
        'accent-btn': '#1a1a1a',
        'chat-banner-bg': '#eef5fb',
        'chat-banner-border': '#d4e6f4',
        'chat-banner-text': '#3a6f8f',
        'card-match-border': '#4090b0',
        'mark-bg': '#ffeab4',
        'toast-bg': '#1a1a1a',
        'toast-text': '#ffffff',
        'tag-general': '#e8e8e8',
        'tag-general-text': '#4a4a4a',
        'tag-arrays': '#d0e8f4',
        'tag-arrays-text': '#2563a0',
        'tag-strings': '#c8e6c8',
        'tag-strings-text': '#2e7d32',
        'tag-sliding-window': '#f4c4d8',
        'tag-sliding-window-text': '#a02060',
        'tag-prefix-sum': '#f4dcc4',
        'tag-prefix-sum-text': '#a05020',
        'tag-hashing': '#dcd8f4',
        'tag-hashing-text': '#4a2da0',
        'tag-trees': '#f4e4c4',
        'tag-trees-text': '#7a5010',
        'tag-graphs': '#c4e8dc',
        'tag-graphs-text': '#1a5a40',
        'tag-dp': '#f4d4d4',
        'tag-dp-text': '#a02020',
        'tag-sorting': '#d4dcf4',
        'tag-sorting-text': '#2a4aa0',
        'tag-backtracking': '#e4e0d4',
        'tag-backtracking-text': '#5a4820',
        'tag-binary-search': '#d4e0f4',
        'tag-binary-search-text': '#2a5090',
        'tag-heaps': '#f4d4e4',
        'tag-heaps-text': '#802060',
        'tag-tries': '#c4f4e8',
        'tag-tries-text': '#1a6858',
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica Neue', 'sans-serif'],
      },
      borderRadius: {
        sm: '6px',
        md: '10px',
        lg: '14px',
        xl: '18px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(0,0,0,0.06)',
        md: '0 2px 6px rgba(0,0,0,0.1)',
      },
    },
  },
  plugins: [],
}
export default config
